name: "Hello User"
description: "A Hello World Action"
author: "Tim Martinez"
inputs:
  url:
    description: "A url to send a get command"
    required: true
    default: "https://google.com"
runs:
  using: "node20"
  main: "index.js"
